version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 043309352934.dkr.ecr.us-east-1.amazonaws.com/cosc1209/final
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t eco-voyage-app .
      - docker tag eco-voyage-app 043309352934.dkr.ecr.us-east-1.amazonaws.com/cosc1209/final:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 043309352934.dkr.ecr.us-east-1.amazonaws.com/cosc1209/final:latest
      - echo Updating ECS service...
      - aws ecs update-service --cluster eco-voyage-cluster --service eco-voyage-service --force-new-deployment